using System.Globalization;
using System.Text.RegularExpressions;
using AutoEQ.Models;

namespace AutoEQ.Linux;

internal sealed partial class LinuxPipeWireEqWriter
{
    private const string PipeWireConfigFileName = "99-autoeq-filter-chain.conf";
    private const string EqFileName = "AutoEQ-PipeWire.txt";
    private readonly string _autoeqConfigDir;
    private readonly string _pipeWireConfigDir;

    public LinuxPipeWireEqWriter()
    {
        string home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        _autoeqConfigDir = Path.Combine(home, ".config", "autoeq");
        _pipeWireConfigDir = Path.Combine(home, ".config", "pipewire", "pipewire.conf.d");
    }

    public string EqFilePath => Path.Combine(_autoeqConfigDir, EqFileName);
    public string PipeWireConfigPath => Path.Combine(_pipeWireConfigDir, PipeWireConfigFileName);
    public bool EqFileExists => File.Exists(EqFilePath);
    public bool PipeWireConfigExists => File.Exists(PipeWireConfigPath);

    public async Task WritePresetAsync(EqPreset preset, CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(_autoeqConfigDir);
        string text = ConvertEqualizerApoToAutoEqParametricText(preset.EqualizerApoText);
        await File.WriteAllTextAsync(EqFilePath, text, cancellationToken).ConfigureAwait(false);
    }

    public async Task WritePipeWireConfigAsync(CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(_pipeWireConfigDir);
        string escapedEqPath = EscapePipeWireString(EqFilePath);
        string config = $$"""
        # Auto-generated by AutoEQ.Linux.
        # Restart PipeWire after changing this file:
        # systemctl --user restart pipewire pipewire-pulse
        #
        # Then select "AutoEQ Sink" as the output device in Ubuntu sound settings.

        context.modules = [
        {   name = libpipewire-module-filter-chain
            args = {
                node.description = "AutoEQ Sink"
                media.name = "AutoEQ Sink"

                filter.graph = {
                    nodes = [
                    {   type = builtin
                        name = eq
                        label = param_eq
                        config = {
                            filename = "{{escapedEqPath}}"
                        }
                    }
                    ]
                }

                capture.props = {
                    node.name = "autoeq_sink"
                    node.description = "AutoEQ Sink"
                    media.class = "Audio/Sink"
                    audio.channels = 2
                    audio.position = [ FL FR ]
                }

                playback.props = {
                    node.name = "autoeq_sink_output"
                    node.passive = true
                    audio.channels = 2
                    audio.position = [ FL FR ]
                }
            }
        }
        ]
        """;

        await File.WriteAllTextAsync(PipeWireConfigPath, config + Environment.NewLine, cancellationToken).ConfigureAwait(false);
    }

    public async Task RestartPipeWireAsync(CancellationToken cancellationToken = default)
    {
        CommandResult result = await CommandRunner.RunAsync(
            "systemctl",
            ["--user", "restart", "pipewire", "pipewire-pulse"],
            cancellationToken).ConfigureAwait(false);

        if (!result.Success)
        {
            throw new InvalidOperationException($"PipeWire restart failed: {result.Error}");
        }
    }

    public async Task TrySetDefaultSinkAsync(CancellationToken cancellationToken = default)
    {
        await CommandRunner.RunAsync("pactl", ["set-default-sink", "autoeq_sink"], cancellationToken).ConfigureAwait(false);
    }

    private static string ConvertEqualizerApoToAutoEqParametricText(string equalizerApoText)
    {
        var lines = new List<string>();
        int index = 1;

        foreach (string rawLine in equalizerApoText.Split(["\r\n", "\n"], StringSplitOptions.None))
        {
            string line = rawLine.Trim();
            if (string.IsNullOrWhiteSpace(line)) continue;

            Match preamp = PreampRegex().Match(line);
            if (preamp.Success)
            {
                lines.Add($"Preamp: {Format(preamp.Groups["gain"].Value)} dB");
                continue;
            }

            Match filter = FilterRegex().Match(line);
            if (!filter.Success) continue;

            string type = filter.Groups["type"].Value.ToUpperInvariant() switch
            {
                "LSC" => "LSC",
                "HSC" => "HSC",
                _ => "PK"
            };

            lines.Add(
                string.Create(
                    CultureInfo.InvariantCulture,
                    $"Filter {index}: ON {type} Fc {Format(filter.Groups["freq"].Value)} Hz Gain {Format(filter.Groups["gain"].Value)} dB Q {Format(filter.Groups["q"].Value)}"));
            index++;
        }

        if (!lines.Any(line => line.StartsWith("Preamp:", StringComparison.OrdinalIgnoreCase)))
        {
            lines.Insert(0, "Preamp: 0 dB");
        }

        return string.Join(Environment.NewLine, lines) + Environment.NewLine;
    }

    private static string Format(string value)
    {
        return double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out double parsed)
            ? parsed.ToString("0.###", CultureInfo.InvariantCulture)
            : value;
    }

    private static string EscapePipeWireString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    [GeneratedRegex(@"^Preamp:\s*(?<gain>[-+]?\d+(?:\.\d+)?)\s*dB", RegexOptions.IgnoreCase)]
    private static partial Regex PreampRegex();

    [GeneratedRegex(@"^Filter:\s*ON\s+(?<type>PK|LSC|HSC)\s+Fc\s+(?<freq>\d+(?:\.\d+)?)\s+Hz\s+Gain\s+(?<gain>[-+]?\d+(?:\.\d+)?)\s+dB\s+Q\s+(?<q>[-+]?\d+(?:\.\d+)?)", RegexOptions.IgnoreCase)]
    private static partial Regex FilterRegex();
}
