using System.Diagnostics;
using System.IO;
using WoburnAutoEQ.Config;
using WoburnAutoEQ.Models;

namespace WoburnAutoEQ.Services;

public sealed class EqualizerApoManager
{
    private const string IncludeLine = "Include: woburn_autoeq.txt";

    public bool IsInstalled() => Directory.Exists(AppConfig.EqualizerApoConfigDir);

    public async Task EnsureIncludeLineAsync()
    {
        if (!Directory.Exists(AppConfig.EqualizerApoConfigDir))
        {
            throw new DirectoryNotFoundException($"Equalizer APO config folder not found: {AppConfig.EqualizerApoConfigDir}");
        }

        if (!File.Exists(AppConfig.EqualizerApoMainConfig))
        {
            await File.WriteAllTextAsync(AppConfig.EqualizerApoMainConfig, string.Empty);
        }

        string current = await File.ReadAllTextAsync(AppConfig.EqualizerApoMainConfig);
        bool exists = current.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None)
            .Any(line => string.Equals(line.Trim(), IncludeLine, StringComparison.OrdinalIgnoreCase));
        if (exists) return;

        string backupPath = AppConfig.EqualizerApoMainConfig + ".bak";
        File.Copy(AppConfig.EqualizerApoMainConfig, backupPath, overwrite: true);
        string separator = current.EndsWith('\n') || current.Length == 0 ? string.Empty : Environment.NewLine;
        await File.WriteAllTextAsync(AppConfig.EqualizerApoMainConfig, current + separator + IncludeLine + Environment.NewLine);
    }

    public async Task WriteWoburnConfigAsync(string text, EqPreset? preset = null, string? reason = null)
    {
        if (!Directory.Exists(AppConfig.EqualizerApoConfigDir))
        {
            throw new DirectoryNotFoundException($"Equalizer APO config folder not found: {AppConfig.EqualizerApoConfigDir}");
        }

        string body = BuildConfigBody(text, preset, reason);
        string tempPath = AppConfig.WoburnEqFile + ".tmp";
        await File.WriteAllTextAsync(tempPath, body);

        if (File.Exists(AppConfig.WoburnEqFile))
        {
            File.Replace(tempPath, AppConfig.WoburnEqFile, null);
        }
        else
        {
            File.Move(tempPath, AppConfig.WoburnEqFile);
        }
    }

    public async Task ApplyPresetAsync(EqPreset preset, string? reason = null)
    {
        try
        {
            await EnsureIncludeLineAsync();
            await WriteWoburnConfigAsync(preset.EqualizerApoText, preset, reason);
        }
        catch (UnauthorizedAccessException ex)
        {
            throw new InvalidOperationException("Please run WoburnAutoEQ as Administrator once to connect with Equalizer APO.", ex);
        }
    }

    public void OpenConfigFolder()
    {
        if (!Directory.Exists(AppConfig.EqualizerApoConfigDir))
        {
            throw new DirectoryNotFoundException($"Equalizer APO config folder not found: {AppConfig.EqualizerApoConfigDir}");
        }

        Process.Start(new ProcessStartInfo
        {
            FileName = AppConfig.EqualizerApoConfigDir,
            UseShellExecute = true
        });
    }

    private static string BuildConfigBody(string text, EqPreset? preset, string? reason)
    {
        var lines = new List<string>
        {
            "# Generated by WoburnAutoEQ. Safe to overwrite.",
            $"# Updated: {DateTimeOffset.Now:yyyy-MM-dd HH:mm:ss zzz}",
        };

        if (preset is not null)
        {
            lines.Add($"# Preset: {preset.Name}");
            lines.Add($"# Type: {(preset.IsDynamic ? "Dynamic AutoEQ" : "Static preset")}");
        }

        if (!string.IsNullOrWhiteSpace(reason))
        {
            lines.Add($"# Reason: {reason}");
        }

        lines.Add(string.Empty);
        lines.Add(text.Trim());
        return string.Join("\r\n", lines) + "\r\n";
    }
}