#pragma checksum "..\..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B1C243F2FCE0FFF8931FB5A494DDB08FAABAFEC5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WoburnAutoEQ {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 286 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DeviceLabel;
        
        #line default
        #line hidden
        
        
        #line 290 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ShortcutLabel;
        
        #line default
        #line hidden
        
        
        #line 301 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SoundCardLabel;
        
        #line default
        #line hidden
        
        
        #line 307 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HeaderSoundOutputLabel;
        
        #line default
        #line hidden
        
        
        #line 319 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MonitoringStatusLabel;
        
        #line default
        #line hidden
        
        
        #line 372 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border AutoEqStatusCard;
        
        #line default
        #line hidden
        
        
        #line 374 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.LinearGradientBrush AutoEqStatusBrush;
        
        #line default
        #line hidden
        
        
        #line 380 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.Effects.DropShadowEffect AutoEqStatusGlow;
        
        #line default
        #line hidden
        
        
        #line 389 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse AutoEqStatusDot;
        
        #line default
        #line hidden
        
        
        #line 392 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AutoEqStatusLabel;
        
        #line default
        #line hidden
        
        
        #line 393 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AutoEqStatusHintLabel;
        
        #line default
        #line hidden
        
        
        #line 395 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox AutoEqCheckBox;
        
        #line default
        #line hidden
        
        
        #line 399 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ManualPresetPanel;
        
        #line default
        #line hidden
        
        
        #line 422 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PresetComboBox;
        
        #line default
        #line hidden
        
        
        #line 453 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line VolumeNeedle;
        
        #line default
        #line hidden
        
        
        #line 458 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.RotateTransform VolumeNeedleTransform;
        
        #line default
        #line hidden
        
        
        #line 467 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox NearWallCheckBox;
        
        #line default
        #line hidden
        
        
        #line 468 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox NightModeCheckBox;
        
        #line default
        #line hidden
        
        
        #line 493 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RecordStatusLabel;
        
        #line default
        #line hidden
        
        
        #line 495 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SongTitleLabel;
        
        #line default
        #line hidden
        
        
        #line 496 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ArtistLabel;
        
        #line default
        #line hidden
        
        
        #line 510 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RecordDeck;
        
        #line default
        #line hidden
        
        
        #line 512 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform RecordSwapScale;
        
        #line default
        #line hidden
        
        
        #line 514 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RecordLayer;
        
        #line default
        #line hidden
        
        
        #line 516 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.RotateTransform RecordRotateTransform;
        
        #line default
        #line hidden
        
        
        #line 546 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SourceLabel;
        
        #line default
        #line hidden
        
        
        #line 572 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MoodSummaryLabel;
        
        #line default
        #line hidden
        
        
        #line 576 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MoodBadgeLabel;
        
        #line default
        #line hidden
        
        
        #line 588 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.UniformGrid WaveBarsPanel;
        
        #line default
        #line hidden
        
        
        #line 589 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border SubBassWaveBar;
        
        #line default
        #line hidden
        
        
        #line 590 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BassWaveBar;
        
        #line default
        #line hidden
        
        
        #line 591 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border LowMidWaveBar;
        
        #line default
        #line hidden
        
        
        #line 592 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border MidWaveBar;
        
        #line default
        #line hidden
        
        
        #line 593 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PresenceWaveBar;
        
        #line default
        #line hidden
        
        
        #line 594 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TrebleWaveBar;
        
        #line default
        #line hidden
        
        
        #line 595 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border AirWaveBar;
        
        #line default
        #line hidden
        
        
        #line 610 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock EnergyLabel;
        
        #line default
        #line hidden
        
        
        #line 611 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar EnergyMeter;
        
        #line default
        #line hidden
        
        
        #line 612 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock EnergyHintLabel;
        
        #line default
        #line hidden
        
        
        #line 618 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BrightnessLabel;
        
        #line default
        #line hidden
        
        
        #line 619 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar BrightnessMeter;
        
        #line default
        #line hidden
        
        
        #line 620 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BrightnessHintLabel;
        
        #line default
        #line hidden
        
        
        #line 633 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BassBandCard;
        
        #line default
        #line hidden
        
        
        #line 636 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BassHintLabel;
        
        #line default
        #line hidden
        
        
        #line 639 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border VocalBandCard;
        
        #line default
        #line hidden
        
        
        #line 642 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock VocalHintLabel;
        
        #line default
        #line hidden
        
        
        #line 645 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TrebleBandCard;
        
        #line default
        #line hidden
        
        
        #line 648 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TrebleHintLabel;
        
        #line default
        #line hidden
        
        
        #line 655 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock GenreLabel;
        
        #line default
        #line hidden
        
        
        #line 658 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AnalysisStateLabel;
        
        #line default
        #line hidden
        
        
        #line 660 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border AutoEqChip;
        
        #line default
        #line hidden
        
        
        #line 661 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AutoEqChipLabel;
        
        #line default
        #line hidden
        
        
        #line 675 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CurrentPresetLabel;
        
        #line default
        #line hidden
        
        
        #line 678 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SoundOutputCountLabel;
        
        #line default
        #line hidden
        
        
        #line 682 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel SoundOutputsPanel;
        
        #line default
        #line hidden
        
        
        #line 694 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ManualActionPanel;
        
        #line default
        #line hidden
        
        
        #line 696 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ApplyButton;
        
        #line default
        #line hidden
        
        
        #line 697 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OpenConfigButton;
        
        #line default
        #line hidden
        
        
        #line 704 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox LogListBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.27.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WoburnAutoEQ;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.27.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DeviceLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.ShortcutLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.SoundCardLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.HeaderSoundOutputLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.MonitoringStatusLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.AutoEqStatusCard = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.AutoEqStatusBrush = ((System.Windows.Media.LinearGradientBrush)(target));
            return;
            case 8:
            this.AutoEqStatusGlow = ((System.Windows.Media.Effects.DropShadowEffect)(target));
            return;
            case 9:
            this.AutoEqStatusDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 10:
            this.AutoEqStatusLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.AutoEqStatusHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.AutoEqCheckBox = ((System.Windows.Controls.CheckBox)(target));
            
            #line 395 "..\..\..\MainWindow.xaml"
            this.AutoEqCheckBox.Checked += new System.Windows.RoutedEventHandler(this.AutoEqCheckBox_StateChanged);
            
            #line default
            #line hidden
            
            #line 395 "..\..\..\MainWindow.xaml"
            this.AutoEqCheckBox.Unchecked += new System.Windows.RoutedEventHandler(this.AutoEqCheckBox_StateChanged);
            
            #line default
            #line hidden
            return;
            case 13:
            this.ManualPresetPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 14:
            this.PresetComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 422 "..\..\..\MainWindow.xaml"
            this.PresetComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.PresetComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 15:
            this.VolumeNeedle = ((System.Windows.Shapes.Line)(target));
            return;
            case 16:
            this.VolumeNeedleTransform = ((System.Windows.Media.RotateTransform)(target));
            return;
            case 17:
            
            #line 463 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.VolumeKnob_MouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 463 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseMove += new System.Windows.Input.MouseEventHandler(this.VolumeKnob_MouseMove);
            
            #line default
            #line hidden
            
            #line 463 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.VolumeKnob_MouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 463 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseWheel += new System.Windows.Input.MouseWheelEventHandler(this.VolumeKnob_MouseWheel);
            
            #line default
            #line hidden
            return;
            case 18:
            this.NearWallCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 19:
            this.NightModeCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 20:
            this.RecordStatusLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.SongTitleLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.ArtistLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            this.RecordDeck = ((System.Windows.Controls.Grid)(target));
            return;
            case 24:
            this.RecordSwapScale = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 25:
            this.RecordLayer = ((System.Windows.Controls.Grid)(target));
            return;
            case 26:
            this.RecordRotateTransform = ((System.Windows.Media.RotateTransform)(target));
            return;
            case 27:
            this.SourceLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 28:
            
            #line 551 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.PreviousButton_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            
            #line 552 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.PlayPauseButton_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            
            #line 553 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NextButton_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            
            #line 554 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.StopMediaButton_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.MoodSummaryLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 33:
            this.MoodBadgeLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 34:
            this.WaveBarsPanel = ((System.Windows.Controls.Primitives.UniformGrid)(target));
            return;
            case 35:
            this.SubBassWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 36:
            this.BassWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 37:
            this.LowMidWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 38:
            this.MidWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 39:
            this.PresenceWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 40:
            this.TrebleWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 41:
            this.AirWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 42:
            this.EnergyLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.EnergyMeter = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 44:
            this.EnergyHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 45:
            this.BrightnessLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 46:
            this.BrightnessMeter = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 47:
            this.BrightnessHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 48:
            this.BassBandCard = ((System.Windows.Controls.Border)(target));
            return;
            case 49:
            this.BassHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 50:
            this.VocalBandCard = ((System.Windows.Controls.Border)(target));
            return;
            case 51:
            this.VocalHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 52:
            this.TrebleBandCard = ((System.Windows.Controls.Border)(target));
            return;
            case 53:
            this.TrebleHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 54:
            this.GenreLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 55:
            this.AnalysisStateLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 56:
            this.AutoEqChip = ((System.Windows.Controls.Border)(target));
            return;
            case 57:
            this.AutoEqChipLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 58:
            this.CurrentPresetLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 59:
            this.SoundOutputCountLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 60:
            this.SoundOutputsPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 61:
            this.ManualActionPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 62:
            this.ApplyButton = ((System.Windows.Controls.Button)(target));
            
            #line 696 "..\..\..\MainWindow.xaml"
            this.ApplyButton.Click += new System.Windows.RoutedEventHandler(this.ApplyButton_Click);
            
            #line default
            #line hidden
            return;
            case 63:
            this.OpenConfigButton = ((System.Windows.Controls.Button)(target));
            
            #line 697 "..\..\..\MainWindow.xaml"
            this.OpenConfigButton.Click += new System.Windows.RoutedEventHandler(this.OpenConfigButton_Click);
            
            #line default
            #line hidden
            return;
            case 64:
            this.LogListBox = ((System.Windows.Controls.ListBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

