using System.Diagnostics;
using System.Globalization;
using System.Text.RegularExpressions;
using AutoEQ.Models;

namespace AutoEQ.Services;

internal sealed partial class PipeWireEqualizerManager : IEqualizerApoManager
{
    private const string PipeWireConfigFileName = "99-autoeq-filter-chain.conf";
    private const string EqFileName = "AutoEQ-PipeWire.txt";
    private readonly string _autoeqConfigDir;
    private readonly string _pipeWireConfigDir;
    private readonly IAppLogger _logger;

    public PipeWireEqualizerManager(IAppLogger logger)
    {
        _logger = logger;
        string home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
        _autoeqConfigDir = Path.Combine(home, ".config", "autoeq");
        _pipeWireConfigDir = Path.Combine(home, ".config", "pipewire", "pipewire.conf.d");
    }

    public string EqFilePath => Path.Combine(_autoeqConfigDir, EqFileName);

    public string PipeWireConfigPath => Path.Combine(_pipeWireConfigDir, PipeWireConfigFileName);

    public bool IsInstalled() => OperatingSystem.IsLinux();

    public async Task EnsureIncludeLineAsync()
    {
        if (!File.Exists(PipeWireConfigPath))
        {
            await WritePipeWireConfigAsync().ConfigureAwait(false);
            _logger.Info($"Đã tạo PipeWire AutoEQ config: {PipeWireConfigPath}");
        }
    }

    public async Task WriteAutoEQConfigAsync(string text, EqPreset? preset = null, string? reason = null)
    {
        await WritePresetTextAsync(text).ConfigureAwait(false);
    }

    public async Task WriteDeviceScopedConfigAsync(string deviceKey, string apoPattern, string text, EqPreset? preset = null, string? reason = null)
    {
        await WritePresetTextAsync(text).ConfigureAwait(false);
    }

    public bool IsLikelyInstalledOnCurrentDevice(AudioOutputInfo? outputInfo) => IsInstalled();

    public async Task ApplyPresetAsync(EqPreset preset, string? reason = null)
    {
        await ApplyPresetAsync(preset, null, reason).ConfigureAwait(false);
    }

    public async Task ApplyPresetAsync(EqPreset preset, AudioOutputInfo? outputInfo, string? reason = null)
    {
        await EnsureIncludeLineAsync().ConfigureAwait(false);
        await WritePresetTextAsync(preset.EqualizerApoText).ConfigureAwait(false);
    }

    public void OpenConfigFolder()
    {
        Directory.CreateDirectory(_autoeqConfigDir);
        Process.Start(new ProcessStartInfo
        {
            FileName = "xdg-open",
            ArgumentList = { _autoeqConfigDir },
            UseShellExecute = false
        });
    }

    private async Task WritePresetTextAsync(string equalizerApoText, CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(_autoeqConfigDir);
        string text = ConvertEqualizerApoToAutoEqParametricText(equalizerApoText);
        await File.WriteAllTextAsync(EqFilePath, text, cancellationToken).ConfigureAwait(false);
    }

    private async Task WritePipeWireConfigAsync(CancellationToken cancellationToken = default)
    {
        Directory.CreateDirectory(_pipeWireConfigDir);
        string escapedEqPath = EscapePipeWireString(EqFilePath);
        string config = $$"""
        # Auto-generated by AutoEQ.
        # Restart PipeWire after changing this file:
        # systemctl --user restart pipewire pipewire-pulse

        context.modules = [
        {   name = libpipewire-module-filter-chain
            args = {
                node.description = "AutoEQ Sink"
                media.name = "AutoEQ Sink"

                filter.graph = {
                    nodes = [
                    {   type = builtin
                        name = eq
                        label = param_eq
                        config = {
                            filename = "{{escapedEqPath}}"
                        }
                    }
                    ]
                }

                capture.props = {
                    node.name = "autoeq_sink"
                    node.description = "AutoEQ Sink"
                    media.class = "Audio/Sink"
                    audio.channels = 2
                    audio.position = [ FL FR ]
                }

                playback.props = {
                    node.name = "autoeq_sink_output"
                    node.passive = true
                    audio.channels = 2
                    audio.position = [ FL FR ]
                }
            }
        }
        ]
        """;

        await File.WriteAllTextAsync(PipeWireConfigPath, config + Environment.NewLine, cancellationToken).ConfigureAwait(false);
    }

    private static string ConvertEqualizerApoToAutoEqParametricText(string equalizerApoText)
    {
        var lines = new List<string>();
        int index = 1;

        foreach (string rawLine in equalizerApoText.Split(["\r\n", "\n"], StringSplitOptions.None))
        {
            string line = rawLine.Trim();
            if (string.IsNullOrWhiteSpace(line)) continue;

            Match preamp = PreampRegex().Match(line);
            if (preamp.Success)
            {
                lines.Add($"Preamp: {Format(preamp.Groups["gain"].Value)} dB");
                continue;
            }

            Match filter = FilterRegex().Match(line);
            if (!filter.Success) continue;

            string type = filter.Groups["type"].Value.ToUpperInvariant() switch
            {
                "LSC" => "LSC",
                "HSC" => "HSC",
                _ => "PK"
            };

            lines.Add(
                string.Create(
                    CultureInfo.InvariantCulture,
                    $"Filter {index}: ON {type} Fc {Format(filter.Groups["freq"].Value)} Hz Gain {Format(filter.Groups["gain"].Value)} dB Q {Format(filter.Groups["q"].Value)}"));
            index++;
        }

        if (!lines.Any(line => line.StartsWith("Preamp:", StringComparison.OrdinalIgnoreCase)))
        {
            lines.Insert(0, "Preamp: 0 dB");
        }

        return string.Join(Environment.NewLine, lines) + Environment.NewLine;
    }

    private static string Format(string value)
    {
        return double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out double parsed)
            ? parsed.ToString("0.###", CultureInfo.InvariantCulture)
            : value;
    }

    private static string EscapePipeWireString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    [GeneratedRegex(@"^Preamp:\s*(?<gain>[-+]?\d+(?:\.\d+)?)\s*dB", RegexOptions.IgnoreCase)]
    private static partial Regex PreampRegex();

    [GeneratedRegex(@"^Filter:\s*ON\s+(?<type>PK|LSC|HSC)\s+Fc\s+(?<freq>\d+(?:\.\d+)?)\s+Hz\s+Gain\s+(?<gain>[-+]?\d+(?:\.\d+)?)\s+dB\s+Q\s+(?<q>[-+]?\d+(?:\.\d+)?)", RegexOptions.IgnoreCase)]
    private static partial Regex FilterRegex();
}
