#pragma checksum "..\..\..\WoburnAutoEQ\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B2E850220DBABBFF9AA264697E93F55876303D93"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WoburnAutoEQ {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 287 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DeviceLabel;
        
        #line default
        #line hidden
        
        
        #line 293 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SoundCardLabel;
        
        #line default
        #line hidden
        
        
        #line 298 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ShortcutLabel;
        
        #line default
        #line hidden
        
        
        #line 308 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MonitoringStatusLabel;
        
        #line default
        #line hidden
        
        
        #line 352 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border AutoEqStatusCard;
        
        #line default
        #line hidden
        
        
        #line 354 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.LinearGradientBrush AutoEqStatusBrush;
        
        #line default
        #line hidden
        
        
        #line 360 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.Effects.DropShadowEffect AutoEqStatusGlow;
        
        #line default
        #line hidden
        
        
        #line 369 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse AutoEqStatusDot;
        
        #line default
        #line hidden
        
        
        #line 372 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AutoEqStatusLabel;
        
        #line default
        #line hidden
        
        
        #line 373 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AutoEqStatusHintLabel;
        
        #line default
        #line hidden
        
        
        #line 375 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox AutoEqCheckBox;
        
        #line default
        #line hidden
        
        
        #line 379 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ManualPresetPanel;
        
        #line default
        #line hidden
        
        
        #line 402 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PresetComboBox;
        
        #line default
        #line hidden
        
        
        #line 433 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Line VolumeNeedle;
        
        #line default
        #line hidden
        
        
        #line 438 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.RotateTransform VolumeNeedleTransform;
        
        #line default
        #line hidden
        
        
        #line 447 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox NearWallCheckBox;
        
        #line default
        #line hidden
        
        
        #line 448 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox NightModeCheckBox;
        
        #line default
        #line hidden
        
        
        #line 472 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RecordStatusLabel;
        
        #line default
        #line hidden
        
        
        #line 473 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SongTitleLabel;
        
        #line default
        #line hidden
        
        
        #line 474 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ArtistLabel;
        
        #line default
        #line hidden
        
        
        #line 488 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RecordDeck;
        
        #line default
        #line hidden
        
        
        #line 490 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform RecordSwapScale;
        
        #line default
        #line hidden
        
        
        #line 492 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RecordLayer;
        
        #line default
        #line hidden
        
        
        #line 494 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.RotateTransform RecordRotateTransform;
        
        #line default
        #line hidden
        
        
        #line 524 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SourceLabel;
        
        #line default
        #line hidden
        
        
        #line 554 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock MoodSummaryLabel;
        
        #line default
        #line hidden
        
        
        #line 575 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.UniformGrid WaveBarsPanel;
        
        #line default
        #line hidden
        
        
        #line 577 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border SubBassWaveBar;
        
        #line default
        #line hidden
        
        
        #line 580 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BassWaveBar;
        
        #line default
        #line hidden
        
        
        #line 583 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border LowMidWaveBar;
        
        #line default
        #line hidden
        
        
        #line 586 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border MidWaveBar;
        
        #line default
        #line hidden
        
        
        #line 589 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PresenceWaveBar;
        
        #line default
        #line hidden
        
        
        #line 592 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TrebleWaveBar;
        
        #line default
        #line hidden
        
        
        #line 595 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border AirWaveBar;
        
        #line default
        #line hidden
        
        
        #line 625 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock EnergyLabel;
        
        #line default
        #line hidden
        
        
        #line 626 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar EnergyMeter;
        
        #line default
        #line hidden
        
        
        #line 627 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock EnergyHintLabel;
        
        #line default
        #line hidden
        
        
        #line 639 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BrightnessLabel;
        
        #line default
        #line hidden
        
        
        #line 640 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar BrightnessMeter;
        
        #line default
        #line hidden
        
        
        #line 641 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BrightnessHintLabel;
        
        #line default
        #line hidden
        
        
        #line 654 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BassBandCard;
        
        #line default
        #line hidden
        
        
        #line 657 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BassHintLabel;
        
        #line default
        #line hidden
        
        
        #line 660 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border VocalBandCard;
        
        #line default
        #line hidden
        
        
        #line 663 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock VocalHintLabel;
        
        #line default
        #line hidden
        
        
        #line 666 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TrebleBandCard;
        
        #line default
        #line hidden
        
        
        #line 669 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TrebleHintLabel;
        
        #line default
        #line hidden
        
        
        #line 676 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock GenreLabel;
        
        #line default
        #line hidden
        
        
        #line 679 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AnalysisStateLabel;
        
        #line default
        #line hidden
        
        
        #line 704 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CurrentPresetLabel;
        
        #line default
        #line hidden
        
        
        #line 708 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SoundOutputCountLabel;
        
        #line default
        #line hidden
        
        
        #line 712 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel SoundOutputsPanel;
        
        #line default
        #line hidden
        
        
        #line 724 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ManualActionPanel;
        
        #line default
        #line hidden
        
        
        #line 726 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ApplyButton;
        
        #line default
        #line hidden
        
        
        #line 727 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OpenConfigButton;
        
        #line default
        #line hidden
        
        
        #line 734 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox LogListBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.27.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WoburnAutoEQ;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.27.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.DeviceLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.SoundCardLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.ShortcutLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.MonitoringStatusLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.AutoEqStatusCard = ((System.Windows.Controls.Border)(target));
            return;
            case 6:
            this.AutoEqStatusBrush = ((System.Windows.Media.LinearGradientBrush)(target));
            return;
            case 7:
            this.AutoEqStatusGlow = ((System.Windows.Media.Effects.DropShadowEffect)(target));
            return;
            case 8:
            this.AutoEqStatusDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 9:
            this.AutoEqStatusLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.AutoEqStatusHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.AutoEqCheckBox = ((System.Windows.Controls.CheckBox)(target));
            
            #line 375 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            this.AutoEqCheckBox.Checked += new System.Windows.RoutedEventHandler(this.AutoEqCheckBox_StateChanged);
            
            #line default
            #line hidden
            
            #line 375 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            this.AutoEqCheckBox.Unchecked += new System.Windows.RoutedEventHandler(this.AutoEqCheckBox_StateChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            this.ManualPresetPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 13:
            this.PresetComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 402 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            this.PresetComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.PresetComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 14:
            this.VolumeNeedle = ((System.Windows.Shapes.Line)(target));
            return;
            case 15:
            this.VolumeNeedleTransform = ((System.Windows.Media.RotateTransform)(target));
            return;
            case 16:
            
            #line 443 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.VolumeKnob_MouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 443 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseMove += new System.Windows.Input.MouseEventHandler(this.VolumeKnob_MouseMove);
            
            #line default
            #line hidden
            
            #line 443 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.VolumeKnob_MouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 443 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseWheel += new System.Windows.Input.MouseWheelEventHandler(this.VolumeKnob_MouseWheel);
            
            #line default
            #line hidden
            return;
            case 17:
            this.NearWallCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 18:
            this.NightModeCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 19:
            this.RecordStatusLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            this.SongTitleLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.ArtistLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 22:
            this.RecordDeck = ((System.Windows.Controls.Grid)(target));
            return;
            case 23:
            this.RecordSwapScale = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 24:
            this.RecordLayer = ((System.Windows.Controls.Grid)(target));
            return;
            case 25:
            this.RecordRotateTransform = ((System.Windows.Media.RotateTransform)(target));
            return;
            case 26:
            this.SourceLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            
            #line 529 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.PreviousButton_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            
            #line 530 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.PlayPauseButton_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            
            #line 531 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NextButton_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            
            #line 532 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.StopMediaButton_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            this.MoodSummaryLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 32:
            this.WaveBarsPanel = ((System.Windows.Controls.Primitives.UniformGrid)(target));
            return;
            case 33:
            this.SubBassWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 34:
            this.BassWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 35:
            this.LowMidWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 36:
            this.MidWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 37:
            this.PresenceWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 38:
            this.TrebleWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 39:
            this.AirWaveBar = ((System.Windows.Controls.Border)(target));
            return;
            case 40:
            this.EnergyLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 41:
            this.EnergyMeter = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 42:
            this.EnergyHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.BrightnessLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 44:
            this.BrightnessMeter = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 45:
            this.BrightnessHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 46:
            this.BassBandCard = ((System.Windows.Controls.Border)(target));
            return;
            case 47:
            this.BassHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 48:
            this.VocalBandCard = ((System.Windows.Controls.Border)(target));
            return;
            case 49:
            this.VocalHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 50:
            this.TrebleBandCard = ((System.Windows.Controls.Border)(target));
            return;
            case 51:
            this.TrebleHintLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 52:
            this.GenreLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 53:
            this.AnalysisStateLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 54:
            this.CurrentPresetLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 55:
            this.SoundOutputCountLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 56:
            this.SoundOutputsPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 57:
            this.ManualActionPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 58:
            this.ApplyButton = ((System.Windows.Controls.Button)(target));
            
            #line 726 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            this.ApplyButton.Click += new System.Windows.RoutedEventHandler(this.ApplyButton_Click);
            
            #line default
            #line hidden
            return;
            case 59:
            this.OpenConfigButton = ((System.Windows.Controls.Button)(target));
            
            #line 727 "..\..\..\WoburnAutoEQ\MainWindow.xaml"
            this.OpenConfigButton.Click += new System.Windows.RoutedEventHandler(this.OpenConfigButton_Click);
            
            #line default
            #line hidden
            return;
            case 60:
            this.LogListBox = ((System.Windows.Controls.ListBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

